#!/usr/bin/env python3
"""Generate golden kernel-params for the Rust Hexagon host from the real llama.cpp C++ source.

    LLAMA_CPP=<llama.cpp checkout> python3 scripts/hexagon-golden/gen.py [op ...]

For each op it extracts the `ggml_hexagon_precompute_<op>_params` function text from
`ggml/src/ggml-hexagon/ggml-hexagon.cpp`, compiles it with `stubs.h` against the real `htp/*.h`
headers, runs the op's case table, and writes `cera/src/backend/hexagon/testdata/<op>_golden.txt`
(one case per line: inputs, then `=>`, then the words of the params blob, or `unsupported`).
The Rust unit tests read those files, so a port is checked against the C it mirrors, word for word.
"""
import os, re, subprocess, sys, tempfile, pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent.parent / "cera/src/backend/hexagon/testdata"
LLAMA = pathlib.Path(os.environ.get("LLAMA_CPP") or sys.exit("set LLAMA_CPP to a llama.cpp checkout"))
SRC = LLAMA / "ggml/src/ggml-hexagon/ggml-hexagon.cpp"
HTP = LLAMA / "ggml/src/ggml-hexagon/htp"


def extract(name: str) -> str:
    """The text of the function DEFINITION `name` (not a forward declaration)."""
    s = SRC.read_text()
    for m in re.finditer(r"^static [^\n;{]*\b%s\s*\(" % re.escape(name), s, re.M):
        # walk the argument list, then require a body
        depth, j = 1, m.end()
        while depth:
            depth += (s[j] == "(") - (s[j] == ")")
            j += 1
        k = j
        while s[k].isspace():
            k += 1
        if s[k] != "{":
            continue
        start = m.start()
        depth = 0
        for e in range(k, len(s)):
            depth += (s[e] == "{") - (s[e] == "}")
            if depth == 0:
                return s[start:e + 1]
    raise SystemExit(f"definition of {name} not found")


def build_and_run(op: str, includes: list[str]) -> str:
    harness = (HERE / f"{op}.cpp").read_text()
    with tempfile.TemporaryDirectory() as d:
        d = pathlib.Path(d)
        # most harnesses wrap a host function; a header-only one (e.g. hmx_chunks) has no fn.inc
        if '"fn.inc"' in harness:
            (d / "fn.inc").write_text(extract(f"ggml_hexagon_precompute_{op}_params"))
        src = "\n".join(f'#include "{i}"' for i in includes) + "\n" + harness
        (d / "main.cpp").write_text(src)
        exe = d / "golden"
        subprocess.check_call(["clang++", "-std=c++17", "-O1", "-w", "-I", str(HERE), "-I", str(HTP), "-I", str(d),
                               str(d / "main.cpp"), "-o", str(exe)])
        return subprocess.check_output([str(exe)], text=True)


OPS = {
    "cpy": ["stubs.h", "hex-common.h", "hex-fastdiv.h", "cpy-ops.h"],
    "concat": ["stubs.h", "hex-common.h", "concat-ops.h"],
    "get_rows": ["stubs.h", "hex-common.h", "hex-fastdiv.h", "get-rows-ops.h"],
    "ssm_conv": ["stubs.h", "hex-common.h", "hex-fastdiv.h", "ssm-conv.h"],
    "hmx_chunks": ["stubs.h", "hex-common.h", "hex-fastdiv.h", "matmul-ops.h"],
    "hmx_solve": ["stubs.h", "hex-common.h", "hex-fastdiv.h", "matmul-ops.h"],
}

if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    rev = subprocess.check_output(["git", "-C", str(LLAMA), "rev-parse", "--short", "HEAD"], text=True).strip()
    for op in (sys.argv[1:] or OPS):
        text = build_and_run(op, OPS[op])
        (OUT / f"{op}_golden.txt").write_text(f"# generated by scripts/hexagon-golden/gen.py from llama.cpp {rev}; do not edit\n" + text)
        print(op, len(text.splitlines()), "cases")
