[package]
name = "loading-web"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cera = { path = "../cera", default-features = false }
cera-wasm = { path = "../cera-wasm", default-features = false }
wasm-bindgen.workspace = true
js-sys = "0.3"
