#!/usr/bin/env python3
"""Generate the Slang kernels of `wgpu_peak_bench` (run from the repository root; compile with
`slangc k.slang -target spirv -O3 -entry main -stage compute -o k.spv`, slangc 2026.19)."""
import os

d = os.path.dirname(os.path.abspath(__file__))
hdr = '''// Generated by gen.py (see the example's docs); do not edit by hand.
struct P { float x; float y; uint iters; uint n_vec; uint a; uint b; uint c; uint d; };
[[vk::binding(0, 0)]] RWStructuredBuffer<float> out_buf;
[[vk::binding(1, 0)]] StructuredBuffer<P> params;
[[vk::binding(2, 0)]] StructuredBuffer<uint4> src;
'''


def fma(ty, chains, name):
    t = f"{ty}4"
    lines = [hdr, "[numthreads(256, 1, 1)]", "void main(uint3 tid : SV_DispatchThreadID) {", "    let p = params[0];"]
    lines.append(f"    {ty} x = {ty}(p.x);")
    lines.append(f"    {ty} y = {ty}(p.y);")
    for i in range(chains):
        lines.append(
            f"    {t} a{i} = {t}({ty}(float(tid.x & 255u) * 0.001), {ty}(0.1), {ty}(0.2), {ty}({0.01 * (i + 1):.2f}));"
        )
    lines.append("    for (uint i = 0u; i < p.iters; i++) {")
    for i in range(chains):
        lines.append(f"        a{i} = a{i} * x + y;")
    lines.append("    }")
    lines.append(f"    {t} s = " + " + ".join(f"a{i}" for i in range(chains)) + ";")
    lines.append("    out_buf[tid.x] = float(s.x + s.y + s.z + s.w);")
    lines.append("}")
    open(f"{d}/{name}.slang", "w").write("\n".join(lines) + "\n")


for chains in (8, 16):
    fma("float", chains, f"fma_f32_c{chains}")
    fma("half", chains, f"fma_f16_c{chains}")

# Packed int8 dot product (SPV_KHR_integer_dot_product): 8 independent accumulators.
lines = [hdr, "[numthreads(256, 1, 1)]", "void main(uint3 tid : SV_DispatchThreadID) {", "    let p = params[0];"]
for i in range(8):
    lines.append(f"    int acc{i} = int(tid.x & 255u) + {i};")
lines.append("    uint wa = p.a; uint wb = p.b;")
lines.append("    for (uint i = 0u; i < p.iters; i++) {")
for i in range(8):
    lines.append(f"        acc{i} = dot4add_i8packed(wa + {i}u, wb, acc{i});")
lines.append("    }")
lines.append("    int s = " + " + ".join(f"acc{i}" for i in range(8)) + ";")
lines.append("    out_buf[tid.x] = float(s);")
lines.append("}")
open(f"{d}/dot_i8_c8.slang", "w").write("\n".join(lines) + "\n")

# Coalesced streaming read of `src`.
lines = [
    hdr,
    "[numthreads(256, 1, 1)]",
    "void main(uint3 tid : SV_DispatchThreadID, uint3 gdim : SV_GroupID) {",
    "    let p = params[0];",
    "    uint total = p.a;  // threads in the dispatch",
    "    uint4 acc = uint4(0u);",
    "    for (uint i = 0u; i < p.iters; i++) {",
    "        acc += src[(i * total + tid.x) % p.n_vec];",
    "    }",
    "    out_buf[tid.x] = float(acc.x ^ acc.y ^ acc.z ^ acc.w);",
    "}",
]
open(f"{d}/bw_read.slang", "w").write("\n".join(lines) + "\n")
