#!/usr/bin/env python3
"""Slang (SPIR-V passthrough) variants of the tiled causal prefill attention, `attention_prefill_hd64.wgsl`,
with fp16 math. A research tool: `cera/examples/wgpu_attn_bench.rs` times them against the f32 kernel and
measures their error against an f64 reference.

The structure is the WGSL kernel's: a workgroup of 128 threads (8 query groups x 16 columns) owns 32 queries
of one head and sweeps the keys 32 at a time. What changes is the precision: Q (pre-scaled by
scale * log2(e)), K^T, V and the probabilities live in shared memory as half, S = QK^T and the PV partial
sums are accumulated in half, and the softmax statistics and the output accumulator stay f32.

Two knobs say how often a half partial sum is widened to f32 and added to an f32 accumulator, which bounds
the rounding error of a long half sum:
  S_BLOCK: QK^T over 64 dims, widened every S_BLOCK dims (64, 32, 16 or 8).
  PV_BLOCK: P V over a 32-key tile, widened every PV_BLOCK keys (32, 16, 8 or 4).

Usage: python3 scripts/attn-fp16/gen.py OUT_DIR   (writes attn_f16_s{S}_p{P}.slang and compiles with slangc)
"""
import os
import shutil
import subprocess
import sys

HEADER = """// Generated by scripts/attn-fp16/gen.py (S_BLOCK={s}, PV_BLOCK={p}); do not edit by hand.
[[vk::binding(0, 0)]] StructuredBuffer<float4> q_batch;
[[vk::binding(1, 0)]] StructuredBuffer<uint2> k_cache;   // packed f16, 4 dims per element
[[vk::binding(2, 0)]] StructuredBuffer<uint2> v_cache;
[[vk::binding(3, 0)]] RWStructuredBuffer<float4> out_batch;
[[vk::binding(4, 0)]] StructuredBuffer<uint> params;

static const float LOG2E = 1.4426950408889634;
static const float NEG = -1.0e30;

groupshared half4 qs[512];     // [d][8 query groups], 4 queries each
groupshared half2 kt[1024];    // K^T: [d][16 key pairs]
groupshared half4 vs[544];     // V: [32 keys][17] (one of padding)
groupshared float ps[1024];    // scores: [32 keys][32 queries]
groupshared half4 ph[256];     // probabilities: [32 keys][8 query groups], 4 queries each
groupshared float pm[128];
groupshared float corr[32];
groupshared float lsum[128];

uint key_window(uint pos, uint bidir, uint prefix, uint total, uint max_seq) {
    uint w = pos + 1u;
    if (bidir != 0u) { w = pos < prefix ? prefix : total; }
    return min(w, max_seq);
}

half4 half4_of(uint2 w) { return reinterpret<half4>(w); }

[numthreads(128, 1, 1)]
void main(uint3 wid : SV_GroupID, uint t : SV_GroupThreadID) {
    uint tx = t % 16u;
    uint ty = t / 16u;
    uint n_head = params[0];
    uint n_kv = params[1];
    uint kv_dim4 = params[3] / 4u;
    uint max_seq = params[4];
    float scale = asfloat(params[5]);
    uint start_pos = params[6];
    uint total = params[7];
    uint q_stride4 = params[8] / 4u;
    uint out_stride4 = params[9] / 4u;
    uint q_base = params[10];
    uint n_sub = params[11];
    uint bidir = params[12];
    uint prefix = params[13];
    uint head = wid.y;
    uint kv_head = head / (n_head / n_kv);
    uint q0 = wid.x * 32u;
    uint last_row = min(q0 + 31u, n_sub - 1u);
    uint wg_limit = key_window(start_pos + q_base + last_row, bidir, prefix, total, max_seq);

    {
        uint qg = t % 8u;
        uint dv = t / 8u;
        float s = scale * LOG2E;
        float4 r0 = q_batch[(q_base + min(q0 + qg * 4u + 0u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        float4 r1 = q_batch[(q_base + min(q0 + qg * 4u + 1u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        float4 r2 = q_batch[(q_base + min(q0 + qg * 4u + 2u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        float4 r3 = q_batch[(q_base + min(q0 + qg * 4u + 3u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        qs[(4u * dv + 0u) * 8u + qg] = half4(half(r0.x), half(r1.x), half(r2.x), half(r3.x));
        qs[(4u * dv + 1u) * 8u + qg] = half4(half(r0.y), half(r1.y), half(r2.y), half(r3.y));
        qs[(4u * dv + 2u) * 8u + qg] = half4(half(r0.z), half(r1.z), half(r2.z), half(r3.z));
        qs[(4u * dv + 3u) * 8u + qg] = half4(half(r0.w), half(r1.w), half(r2.w), half(r3.w));
    }
    uint lim0 = key_window(start_pos + q_base + min(q0 + ty * 4u + 0u, n_sub - 1u), bidir, prefix, total, max_seq);
    uint lim1 = key_window(start_pos + q_base + min(q0 + ty * 4u + 1u, n_sub - 1u), bidir, prefix, total, max_seq);
    uint lim2 = key_window(start_pos + q_base + min(q0 + ty * 4u + 2u, n_sub - 1u), bidir, prefix, total, max_seq);
    uint lim3 = key_window(start_pos + q_base + min(q0 + ty * 4u + 3u, n_sub - 1u), bidir, prefix, total, max_seq);

    float4 o0 = float4(0.0); float4 o1 = float4(0.0); float4 o2 = float4(0.0); float4 o3 = float4(0.0);
    uint sq = t % 32u;
    uint sp = t / 32u;
    float m = NEG;
    float l = 0.0;

    for (uint kb = 0u; kb < wg_limit; kb += 32u) {
"""


TAIL = """        GroupMemoryBarrierWithGroupSync();
    }

    lsum[sp * 32u + sq] = l;
    GroupMemoryBarrierWithGroupSync();
    uint r0 = q0 + ty * 4u;
    float s0 = lsum[ty * 4u] + lsum[32u + ty * 4u] + lsum[64u + ty * 4u] + lsum[96u + ty * 4u];
    float s1 = lsum[ty * 4u + 1u] + lsum[32u + ty * 4u + 1u] + lsum[64u + ty * 4u + 1u] + lsum[96u + ty * 4u + 1u];
    float s2 = lsum[ty * 4u + 2u] + lsum[32u + ty * 4u + 2u] + lsum[64u + ty * 4u + 2u] + lsum[96u + ty * 4u + 2u];
    float s3 = lsum[ty * 4u + 3u] + lsum[32u + ty * 4u + 3u] + lsum[64u + ty * 4u + 3u] + lsum[96u + ty * 4u + 3u];
    float i0 = s0 > 0.0 ? 1.0 / s0 : 0.0;
    float i1 = s1 > 0.0 ? 1.0 / s1 : 0.0;
    float i2 = s2 > 0.0 ? 1.0 / s2 : 0.0;
    float i3 = s3 > 0.0 ? 1.0 / s3 : 0.0;
    if (r0 + 0u < n_sub) { out_batch[(q_base + r0 + 0u) * out_stride4 + head * 16u + tx] = o0 * i0; }
    if (r0 + 1u < n_sub) { out_batch[(q_base + r0 + 1u) * out_stride4 + head * 16u + tx] = o1 * i1; }
    if (r0 + 2u < n_sub) { out_batch[(q_base + r0 + 2u) * out_stride4 + head * 16u + tx] = o2 * i2; }
    if (r0 + 3u < n_sub) { out_batch[(q_base + r0 + 3u) * out_stride4 + head * 16u + tx] = o3 * i3; }
}"""


def gen(s_block, pv_block, skip=()):
    """`skip` names phases to remove for an ablation (the output is then wrong): 'stage' (the K^T and V
    loads), 's' (QK^T), 'pv' (P V), 'soft' (the exp2s)."""
    L = [HEADER.replace("{s}", str(s_block)).replace("{p}", str(pv_block))]
    if "stage" not in skip:
        for unit in range(2):  # K^T block: 2 keys x 4 dims per unit, 2 units per thread
            L.append(f"""        {{
            uint u = t + 128u * {unit}u;
            uint kp = u % 16u;
            uint dv = u / 16u;
            uint ra = kb + kp * 2u;
            half4 a = half4(0.0h);
            half4 b = half4(0.0h);
            if (ra < wg_limit) {{ a = half4_of(k_cache[ra * kv_dim4 + kv_head * 16u + dv]); }}
            if (ra + 1u < wg_limit) {{ b = half4_of(k_cache[(ra + 1u) * kv_dim4 + kv_head * 16u + dv]); }}
            kt[(4u * dv + 0u) * 16u + kp] = half2(a.x, b.x);
            kt[(4u * dv + 1u) * 16u + kp] = half2(a.y, b.y);
            kt[(4u * dv + 2u) * 16u + kp] = half2(a.z, b.z);
            kt[(4u * dv + 3u) * 16u + kp] = half2(a.w, b.w);
        }}""")
    L.append("        GroupMemoryBarrierWithGroupSync();\n")
    L.append("        float2 sf0 = float2(0.0); float2 sf1 = float2(0.0); float2 sf2 = float2(0.0); float2 sf3 = float2(0.0);")
    if "s" not in skip:
        L.append("        [loop] for (uint db = 0u; db < 64u; db += %du) {" % s_block)
        L.append("            half2 s0 = half2(0.0h); half2 s1 = half2(0.0h); half2 s2 = half2(0.0h); half2 s3 = half2(0.0h);")
        for j in range(s_block):
            L.append(f"""            {{
                half4 qv = qs[(db + {j}u) * 8u + ty];
                half2 kv = kt[(db + {j}u) * 16u + tx];
                s0 += qv.x * kv; s1 += qv.y * kv; s2 += qv.z * kv; s3 += qv.w * kv;
            }}""")
        L.append("            sf0 += float2(s0); sf1 += float2(s1); sf2 += float2(s2); sf3 += float2(s3);")
        L.append("        }")
    L.append("""        uint key0 = kb + tx * 2u;
        uint pb0 = (tx * 2u + 0u) * 32u + ty * 4u;
        uint pb1 = (tx * 2u + 1u) * 32u + ty * 4u;
        ps[pb0] = key0 < lim0 ? sf0.x : NEG;
        ps[pb0 + 1u] = key0 < lim1 ? sf1.x : NEG;
        ps[pb0 + 2u] = key0 < lim2 ? sf2.x : NEG;
        ps[pb0 + 3u] = key0 < lim3 ? sf3.x : NEG;
        ps[pb1] = key0 + 1u < lim0 ? sf0.y : NEG;
        ps[pb1 + 1u] = key0 + 1u < lim1 ? sf1.y : NEG;
        ps[pb1 + 2u] = key0 + 1u < lim2 ? sf2.y : NEG;
        ps[pb1 + 3u] = key0 + 1u < lim3 ? sf3.y : NEG;
        GroupMemoryBarrierWithGroupSync();
""")
    if "stage" not in skip:
        for unit in range(4):  # V block
            L.append(f"""        {{
            uint idx = t + 128u * {unit}u;
            uint kj = idx / 16u;
            uint dv = idx % 16u;
            uint row = kb + kj;
            half4 x = half4(0.0h);
            if (row < wg_limit) {{ x = half4_of(v_cache[row * kv_dim4 + kv_head * 16u + dv]); }}
            vs[kj * 17u + dv] = x;
        }}""")
    L.append("        float pmax = NEG;")
    for i in range(8):
        L.append(f"        float x{i} = ps[(sp * 8u + {i}u) * 32u + sq]; pmax = max(pmax, x{i});")
    c_expr = "(m - m_new)" if "soft" in skip else "exp2(m - m_new)"
    L.append("""        pm[sp * 32u + sq] = pmax;
        GroupMemoryBarrierWithGroupSync();
        float m_new = max(max(m, max(pm[sq], pm[32u + sq])), max(pm[64u + sq], pm[96u + sq]));
        float c = %s;
        float psum = 0.0;""" % c_expr)
    for i in range(8):
        e = f"(x{i} - m_new)" if "soft" in skip else f"exp2(x{i} - m_new)"
        L.append(f"        float p{i} = {e}; psum += p{i};")
    for i in range(8):
        L.append(f"        ps[(sp * 8u + {i}u) * 32u + sq] = p{i};")
    L.append("""        l = l * c + psum;
        m = m_new;
        if (sp == 0u) { corr[sq] = c; }
        GroupMemoryBarrierWithGroupSync();
        for (uint z = 0u; z < 2u; z++) {
            uint e = t + 128u * z;
            uint key = e / 8u;
            uint qg = e % 8u;
            ph[e] = half4(half(ps[key * 32u + qg * 4u]), half(ps[key * 32u + qg * 4u + 1u]),
                          half(ps[key * 32u + qg * 4u + 2u]), half(ps[key * 32u + qg * 4u + 3u]));
        }
        GroupMemoryBarrierWithGroupSync();
        o0 *= corr[ty * 4u + 0u];
        o1 *= corr[ty * 4u + 1u];
        o2 *= corr[ty * 4u + 2u];
        o3 *= corr[ty * 4u + 3u];""")
    if "pv" not in skip:
        L.append("        [loop] for (uint jb = 0u; jb < 32u; jb += %du) {" % pv_block)
        L.append("            half4 a0 = half4(0.0h); half4 a1 = half4(0.0h); half4 a2 = half4(0.0h); half4 a3 = half4(0.0h);")
        for j in range(pv_block):
            L.append(f"""            {{
                half4 pv = ph[(jb + {j}u) * 8u + ty];
                half4 vv = vs[(jb + {j}u) * 17u + tx];
                a0 += pv.x * vv; a1 += pv.y * vv; a2 += pv.z * vv; a3 += pv.w * vv;
            }}""")
        L.append("            o0 += float4(a0); o1 += float4(a1); o2 += float4(a2); o3 += float4(a3);")
        L.append("        }")
    L.append(TAIL)
    return "\n".join(L) + "\n"


def gen_t44(dt, s_block=8, pv_block=4):
    """The 4 x 4 tile variant: a workgroup of 64 threads (8 query groups x 8 key quads) owns 32 queries; a
    thread's S tile is 4 queries x 4 keys, so the QK^T FMAs are 4 lanes wide (the 128-thread kernels
    above use 4 x 2 and 2-lane FMAs), and its PV tile is 4 queries x 8 dims. `dt` is "half" or "float"
    (the type of the shared tiles and the FMAs; the softmax and the output accumulator are f32 either way)."""
    T, T4, Z = dt, dt + "4", ("0.0h" if dt == "half" else "0.0")
    widen_s = dt == "half"
    cv = (lambda e: f"float4({e})") if dt == "half" else (lambda e: e)  # widen a T4 to float4
    ld = (lambda e: e) if dt == "half" else (lambda e: f"float4({e})")  # f16 words -> T4
    H = HEADER.replace("{s}", str(s_block)).replace("{p}", str(pv_block))
    # retarget the shared declarations and the 128-thread header parts
    H = H.replace("groupshared half4 qs[512];     // [d][8 query groups], 4 queries each", f"groupshared {T4} qs[512];")
    H = H.replace("groupshared half2 kt[1024];    // K^T: [d][16 key pairs]", f"groupshared {T4} kt[512];     // K^T: [d][8 key quads]")
    H = H.replace("groupshared half4 vs[544];     // V: [32 keys][17] (one of padding)", f"groupshared {T4} vs[544];")
    H = H.replace("groupshared half4 ph[256];     // probabilities: [32 keys][8 query groups], 4 queries each", f"groupshared {T4} ph[256];")
    H = H.replace("groupshared float pm[128];", "groupshared float pm[64];").replace("groupshared float lsum[128];", "groupshared float lsum[64];")
    H = H.replace("[numthreads(128, 1, 1)]", "[numthreads(64, 1, 1)]")
    # thread mapping: tx = key quad / dim octet (8), ty = query group (8)
    H = H.replace("uint tx = t % 16u;\n    uint ty = t / 16u;", "uint tx = t % 8u;\n    uint ty = t / 8u;")
    # Q staging: 2 units per thread
    qi = H.index("    {\n        uint qg = t % 8u;")
    qj = H.index("    uint lim0")
    H = H[:qi] + f"""    for (uint z = 0u; z < 2u; z++) {{
        uint id = t + 64u * z;
        uint qg = id % 8u;
        uint dv = id / 8u;
        float s = scale * LOG2E;
        float4 r0 = q_batch[(q_base + min(q0 + qg * 4u + 0u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        float4 r1 = q_batch[(q_base + min(q0 + qg * 4u + 1u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        float4 r2 = q_batch[(q_base + min(q0 + qg * 4u + 2u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        float4 r3 = q_batch[(q_base + min(q0 + qg * 4u + 3u, n_sub - 1u)) * q_stride4 + head * 16u + dv] * s;
        qs[(4u * dv + 0u) * 8u + qg] = {T4}({T}(r0.x), {T}(r1.x), {T}(r2.x), {T}(r3.x));
        qs[(4u * dv + 1u) * 8u + qg] = {T4}({T}(r0.y), {T}(r1.y), {T}(r2.y), {T}(r3.y));
        qs[(4u * dv + 2u) * 8u + qg] = {T4}({T}(r0.z), {T}(r1.z), {T}(r2.z), {T}(r3.z));
        qs[(4u * dv + 3u) * 8u + qg] = {T4}({T}(r0.w), {T}(r1.w), {T}(r2.w), {T}(r3.w));
    }}
""" + H[qj:]
    # output accumulators: 4 queries x 2 float4; softmax roles: 2 threads per query
    H = H.replace("    float4 o0 = float4(0.0); float4 o1 = float4(0.0); float4 o2 = float4(0.0); float4 o3 = float4(0.0);\n    uint sq = t % 32u;\n    uint sp = t / 32u;",
                  "    float4 o0a = float4(0.0); float4 o0b = float4(0.0); float4 o1a = float4(0.0); float4 o1b = float4(0.0);\n    float4 o2a = float4(0.0); float4 o2b = float4(0.0); float4 o3a = float4(0.0); float4 o3b = float4(0.0);\n    uint sq = t % 32u;\n    uint sp = t / 32u;")
    L = [H]
    # K^T: 2 units per thread, a unit = 4 keys x 4 dims
    for u in range(2):
        L.append(f"""        {{
            uint id = t + 64u * {u}u;
            uint kq = id % 8u;
            uint dv = id / 8u;
            uint ra = kb + kq * 4u;
            {T4} a0 = {T4}({Z}); {T4} a1 = {T4}({Z}); {T4} a2 = {T4}({Z}); {T4} a3 = {T4}({Z});
            if (ra + 0u < wg_limit) {{ a0 = {ld('half4_of(k_cache[(ra + 0u) * kv_dim4 + kv_head * 16u + dv])')}; }}
            if (ra + 1u < wg_limit) {{ a1 = {ld('half4_of(k_cache[(ra + 1u) * kv_dim4 + kv_head * 16u + dv])')}; }}
            if (ra + 2u < wg_limit) {{ a2 = {ld('half4_of(k_cache[(ra + 2u) * kv_dim4 + kv_head * 16u + dv])')}; }}
            if (ra + 3u < wg_limit) {{ a3 = {ld('half4_of(k_cache[(ra + 3u) * kv_dim4 + kv_head * 16u + dv])')}; }}
            kt[(4u * dv + 0u) * 8u + kq] = {T4}(a0.x, a1.x, a2.x, a3.x);
            kt[(4u * dv + 1u) * 8u + kq] = {T4}(a0.y, a1.y, a2.y, a3.y);
            kt[(4u * dv + 2u) * 8u + kq] = {T4}(a0.z, a1.z, a2.z, a3.z);
            kt[(4u * dv + 3u) * 8u + kq] = {T4}(a0.w, a1.w, a2.w, a3.w);
        }}""")
    L.append("        GroupMemoryBarrierWithGroupSync();\n")
    L.append("        float4 sf0 = float4(0.0); float4 sf1 = float4(0.0); float4 sf2 = float4(0.0); float4 sf3 = float4(0.0);")
    blk = s_block if widen_s else 64
    L.append("        [loop] for (uint db = 0u; db < 64u; db += %du) {" % blk)
    L.append(f"            {T4} s0 = {T4}({Z}); {T4} s1 = {T4}({Z}); {T4} s2 = {T4}({Z}); {T4} s3 = {T4}({Z});" if widen_s else "")
    for j in range(blk):
        L.append(f"""            {{
                {T4} qv = qs[(db + {j}u) * 8u + ty];
                {T4} kv = kt[(db + {j}u) * 8u + tx];
                {"s0 += qv.x * kv; s1 += qv.y * kv; s2 += qv.z * kv; s3 += qv.w * kv;" if widen_s else "sf0 += qv.x * kv; sf1 += qv.y * kv; sf2 += qv.z * kv; sf3 += qv.w * kv;"}
            }}""")
    if widen_s:
        L.append("            sf0 += float4(s0); sf1 += float4(s1); sf2 += float4(s2); sf3 += float4(s3);")
    L.append("        }")
    # mask + store scores (16 per thread)
    L.append("        uint key0 = kb + tx * 4u;")
    for c in range(4):
        for i in range(4):
            L.append(f"        ps[(tx * 4u + {c}u) * 32u + ty * 4u + {i}u] = key0 + {c}u < lim{i} ? sf{i}.{'xyzw'[c]} : NEG;")
    L.append("        GroupMemoryBarrierWithGroupSync();\n")
    # V staging: 8 units per thread
    for u in range(8):
        L.append(f"""        {{
            uint id = t + 64u * {u}u;
            uint kj = id / 16u;
            uint dv = id % 16u;
            uint row = kb + kj;
            {T4} x = {T4}({Z});
            if (row < wg_limit) {{ x = {ld('half4_of(v_cache[row * kv_dim4 + kv_head * 16u + dv])')}; }}
            vs[kj * 17u + dv] = x;
        }}""")
    # softmax: 2 threads per query, 16 keys each
    L.append("        float pmax = NEG;")
    for i in range(16):
        L.append(f"        float x{i} = ps[(sp * 16u + {i}u) * 32u + sq]; pmax = max(pmax, x{i});")
    L.append("""        pm[sp * 32u + sq] = pmax;
        GroupMemoryBarrierWithGroupSync();
        float m_new = max(m, max(pm[sq], pm[32u + sq]));
        float c = exp2(m - m_new);
        float psum = 0.0;""")
    for i in range(16):
        L.append(f"        float p{i} = exp2(x{i} - m_new); psum += p{i};")
    for i in range(16):
        L.append(f"        ps[(sp * 16u + {i}u) * 32u + sq] = p{i};")
    L.append(f"""        l = l * c + psum;
        m = m_new;
        if (sp == 0u) {{ corr[sq] = c; }}
        GroupMemoryBarrierWithGroupSync();
        for (uint z = 0u; z < 4u; z++) {{
            uint e = t + 64u * z;
            uint key = e / 8u;
            uint qg = e % 8u;
            ph[e] = {T4}({T}(ps[key * 32u + qg * 4u]), {T}(ps[key * 32u + qg * 4u + 1u]),
                          {T}(ps[key * 32u + qg * 4u + 2u]), {T}(ps[key * 32u + qg * 4u + 3u]));
        }}
        GroupMemoryBarrierWithGroupSync();
        float cc0 = corr[ty * 4u + 0u]; float cc1 = corr[ty * 4u + 1u]; float cc2 = corr[ty * 4u + 2u]; float cc3 = corr[ty * 4u + 3u];
        o0a *= cc0; o0b *= cc0; o1a *= cc1; o1b *= cc1; o2a *= cc2; o2b *= cc2; o3a *= cc3; o3b *= cc3;""")
    pb = pv_block if widen_s else 32
    L.append("        [loop] for (uint jb = 0u; jb < 32u; jb += %du) {" % pb)
    if widen_s:
        L.append("            half4 a0a = half4(0.0h); half4 a0b = half4(0.0h); half4 a1a = half4(0.0h); half4 a1b = half4(0.0h);\n            half4 a2a = half4(0.0h); half4 a2b = half4(0.0h); half4 a3a = half4(0.0h); half4 a3b = half4(0.0h);")
    for j in range(pb):
        acc = (lambda i, h: f"a{i}{h}") if widen_s else (lambda i, h: f"o{i}{h}")
        L.append(f"""            {{
                {T4} pv = ph[(jb + {j}u) * 8u + ty];
                {T4} v0 = vs[(jb + {j}u) * 17u + tx * 2u];
                {T4} v1 = vs[(jb + {j}u) * 17u + tx * 2u + 1u];
                {acc(0,'a')} += pv.x * v0; {acc(0,'b')} += pv.x * v1;
                {acc(1,'a')} += pv.y * v0; {acc(1,'b')} += pv.y * v1;
                {acc(2,'a')} += pv.z * v0; {acc(2,'b')} += pv.z * v1;
                {acc(3,'a')} += pv.w * v0; {acc(3,'b')} += pv.w * v1;
            }}""")
    if widen_s:
        L.append("            o0a += float4(a0a); o0b += float4(a0b); o1a += float4(a1a); o1b += float4(a1b);\n            o2a += float4(a2a); o2b += float4(a2b); o3a += float4(a3a); o3b += float4(a3b);")
    L.append("        }")
    L.append("""        GroupMemoryBarrierWithGroupSync();
    }

    lsum[sp * 32u + sq] = l;
    GroupMemoryBarrierWithGroupSync();
    uint r0 = q0 + ty * 4u;
    float s0 = lsum[ty * 4u] + lsum[32u + ty * 4u];
    float s1 = lsum[ty * 4u + 1u] + lsum[32u + ty * 4u + 1u];
    float s2 = lsum[ty * 4u + 2u] + lsum[32u + ty * 4u + 2u];
    float s3 = lsum[ty * 4u + 3u] + lsum[32u + ty * 4u + 3u];
    float i0 = s0 > 0.0 ? 1.0 / s0 : 0.0;
    float i1 = s1 > 0.0 ? 1.0 / s1 : 0.0;
    float i2 = s2 > 0.0 ? 1.0 / s2 : 0.0;
    float i3 = s3 > 0.0 ? 1.0 / s3 : 0.0;
    if (r0 + 0u < n_sub) { out_batch[(q_base + r0 + 0u) * out_stride4 + head * 16u + tx * 2u] = o0a * i0; out_batch[(q_base + r0 + 0u) * out_stride4 + head * 16u + tx * 2u + 1u] = o0b * i0; }
    if (r0 + 1u < n_sub) { out_batch[(q_base + r0 + 1u) * out_stride4 + head * 16u + tx * 2u] = o1a * i1; out_batch[(q_base + r0 + 1u) * out_stride4 + head * 16u + tx * 2u + 1u] = o1b * i1; }
    if (r0 + 2u < n_sub) { out_batch[(q_base + r0 + 2u) * out_stride4 + head * 16u + tx * 2u] = o2a * i2; out_batch[(q_base + r0 + 2u) * out_stride4 + head * 16u + tx * 2u + 1u] = o2b * i2; }
    if (r0 + 3u < n_sub) { out_batch[(q_base + r0 + 3u) * out_stride4 + head * 16u + tx * 2u] = o3a * i3; out_batch[(q_base + r0 + 3u) * out_stride4 + head * 16u + tx * 2u + 1u] = o3b * i3; }
}""")
    return "\n".join(L) + "\n"


VARIANTS = [(8, 4), (8, 8), (16, 8), (16, 16), (32, 16)]

if __name__ == "__main__":
    out = next((a for a in sys.argv[1:] if not a.startswith("--")), "attn_f16")
    os.makedirs(out, exist_ok=True)
    slangc = os.environ.get("SLANGC") or shutil.which("slangc") or os.path.expanduser("~/.local/slang/bin/slangc")
    jobs = [(f"attn_f16_s{s}_p{p}", s, p, ()) for s, p in VARIANTS]
    if "--ablate" in sys.argv:
        jobs += [(f"abl_no_{ph}", 8, 4, (ph,)) for ph in ("stage", "s", "pv", "soft")]
        jobs.append(("abl_only_softmax", 8, 4, ("stage", "s", "pv")))
    texts = {}
    for name, s_, p_, skip in jobs:
        texts[name] = gen(s_, p_, skip)
    texts["attn_t44_half"] = gen_t44("half")
    texts["attn_t44_float"] = gen_t44("float")
    jobs += [("attn_t44_half", 0, 0, ()), ("attn_t44_float", 0, 0, ())]
    for name, s_, p_, skip in jobs:
        open(os.path.join(out, name + ".slang"), "w").write(texts[name])
        r = subprocess.run([slangc, os.path.join(out, name + ".slang"), "-target", "spirv", "-O3", "-entry", "main",
                            "-stage", "compute", "-o", os.path.join(out, name + ".spv")], capture_output=True, text=True)
        print(("ok   " if r.returncode == 0 else "FAIL ") + name, r.stderr[:400])
