"""Python bindings for cera inference engine."""

from .cera_ffi import (
    CeraEngine,
    ChatSession,
    EngineConfig,
    FfiEntitySpan,
    FinishReason,
    GenerateOpts,
    Message,
    ModalitySink,
    PiiClassifier,
    Role,
    Session,
    SessionPhase,
    TurnResult,
    ValidationError,
    chat_message_assistant,
    chat_message_system,
    chat_message_tool,
    chat_message_user,
    chat_stream,
    chat_stream_json,
    with_json_schema,
    json_schema_to_grammar,
)


__all__ = [
    "CeraEngine",
    "ChatSession",
    "EngineConfig",
    "FfiEntitySpan",
    "FinishReason",
    "GenerateOpts",
    "Message",
    "ModalitySink",
    "PiiClassifier",
    "Role",
    "Session",
    "SessionPhase",
    "TurnResult",
    "ValidationError",
    "chat_message_assistant",
    "chat_message_system",
    "chat_message_tool",
    "chat_message_user",
    "chat_stream",
    "chat_stream_json",
    "json_schema_to_grammar",
    "with_json_schema",
]
