use std::process::Command;

// Embeds a best-effort short git SHA into the build for provenance
// (`cera::build_info()` / `cera::GIT_SHA`). Consumers such as the Pipette
// benchmark app report it alongside results, the way llama.cpp surfaces its
// build commit. Falls back to "unknown" when git is unavailable (e.g. a
// packaged source build with no repository), and can be overridden explicitly
// by setting `CERA_GIT_SHA` in the build environment (used by release CI for a
// deterministic value).
fn main() {
    // An explicit env value wins — lets release pipelines pin the sha without
    // depending on a `.git` directory being present at build time.
    let sha = std::env::var("CERA_GIT_SHA").ok().unwrap_or_else(|| {
        Command::new("git")
            .args(["rev-parse", "--short=12", "HEAD"])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "unknown".to_string())
    });
    println!("cargo:rustc-env=CERA_GIT_SHA={sha}");
    println!("cargo:rerun-if-env-changed=CERA_GIT_SHA");

    // Compile the Slang SPIR-V passthrough kernels (gpu feature only). Each is
    // written to OUT_DIR and `include_spirv_raw!`d from there, so slangc is the
    // source of truth. When slangc is unavailable (e.g. CI without a Slang
    // toolchain) we fall back to the committed `.spv` next to the `.slang`, which
    // a developer with slangc regenerates via `just slang`; a cargo:warning
    // flags the fallback so drift is visible.
    if std::env::var_os("CARGO_FEATURE_GPU").is_some() {
        compile_slang_kernels();
    }

    // Multi-target Slang kernels: one `.slang` emitted to WGSL *and* MSL, so the
    // two GPU backends share a source instead of two hand-maintained twins.
    // Unlike the SPIR-V passthrough kernels above this is not Vulkan-specific,
    // so it runs for either GPU feature and emits only the targets that feature
    // needs.
    let want_wgsl = std::env::var_os("CARGO_FEATURE_GPU").is_some();
    let want_msl = std::env::var_os("CARGO_FEATURE_METAL").is_some();
    if want_wgsl || want_msl {
        compile_slang_multitarget(want_wgsl, want_msl);
    }
}

/// Slang passthrough kernels, by basename under `src/backend/shaders/spirv/`.
/// Extend as loaders are ported; each needs a `<name>.slang` and a committed
/// `<name>.spv` fallback.
const SLANG_KERNELS: &[&str] = &[
    "mul_mat_reg_tile_q4_0",
    "mul_mat_reg_tile_q8_0",
    "mul_mat_reg_tile_q4_k",
    "mul_mat_reg_tile_q5_k",
    "mul_mat_reg_tile_q6_k",
];

fn compile_slang_kernels() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR unset");
    let dir = "src/backend/shaders/spirv";
    let slangc = find_slangc();

    for name in SLANG_KERNELS {
        let src = format!("{dir}/{name}.slang");
        let committed = format!("{dir}/{name}.spv");
        let out = format!("{out_dir}/{name}.spv");
        println!("cargo:rerun-if-changed={src}");
        println!("cargo:rerun-if-changed={committed}");

        let compiled = slangc.as_ref().is_some_and(|sc| {
            Command::new(sc)
                .args([
                    src.as_str(),
                    "-target",
                    "spirv",
                    "-O3",
                    "-entry",
                    "main",
                    "-stage",
                    "compute",
                    "-o",
                    out.as_str(),
                ])
                .status()
                .map(|s| s.success())
                .unwrap_or(false)
        });

        if !compiled {
            if slangc.is_none() {
                println!(
                    "cargo:warning=slangc not found; using committed {name}.spv. Set SLANGC or add ~/.local/slang/bin to PATH to recompile from {name}.slang."
                );
            } else {
                println!(
                    "cargo:warning=slangc failed on {name}.slang; using committed {name}.spv."
                );
            }
            std::fs::copy(&committed, &out)
                .unwrap_or_else(|e| panic!("no compiled or committed SPIR-V for {name}: {e}"));
        }
    }
    println!("cargo:rerun-if-env-changed=SLANGC");
}

/// Multi-target Slang kernels, by basename under `src/backend/shaders/slang/`.
/// Each needs a `<name>.slang` plus committed `<name>.wgsl` / `<name>.metal`
/// fallbacks for build hosts without slangc, regenerated by `just slang`.
const SLANG_MULTI_KERNELS: &[&str] = &["softmax", "coopmat_probe", "gemm_q8_0"];

/// Compile each multi-target kernel to the shader languages the enabled
/// features actually need.
///
/// Same fallback contract as [`compile_slang_kernels`]: slangc is the source of
/// truth, the committed output is copied when it is unavailable, and a
/// `cargo:warning` makes the fallback visible so drift cannot pass silently.
/// The emitted text is `include_str!`'d from OUT_DIR, so a stale committed file
/// never wins over a successful compile.
fn compile_slang_multitarget(want_wgsl: bool, want_msl: bool) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR unset");
    let dir = "src/backend/shaders/slang";
    let slangc = find_slangc();

    // (slangc target name, file extension). Extension doubles as the committed
    // fallback's suffix, so the two can never disagree.
    let mut targets: Vec<(&str, &str)> = Vec::new();
    if want_wgsl {
        targets.push(("wgsl", "wgsl"));
    }
    if want_msl {
        targets.push(("metal", "metal"));
    }

    for name in SLANG_MULTI_KERNELS {
        let src = format!("{dir}/{name}.slang");
        println!("cargo:rerun-if-changed={src}");

        for (target, ext) in &targets {
            let committed = format!("{dir}/{name}.{ext}");
            let out = format!("{out_dir}/{name}.{ext}");
            println!("cargo:rerun-if-changed={committed}");

            let compiled = slangc.as_ref().is_some_and(|sc| {
                Command::new(sc)
                    .args([
                        src.as_str(),
                        "-target",
                        target,
                        "-O3",
                        "-entry",
                        name,
                        "-stage",
                        "compute",
                        "-o",
                        out.as_str(),
                    ])
                    .status()
                    .map(|s| s.success())
                    .unwrap_or(false)
            });

            if !compiled {
                if slangc.is_none() {
                    println!(
                        "cargo:warning=slangc not found; using committed {name}.{ext}. Set SLANGC or add ~/.local/slang/bin to PATH to recompile from {name}.slang."
                    );
                } else {
                    println!(
                        "cargo:warning=slangc failed on {name}.slang for target {target}; using committed {name}.{ext}."
                    );
                }
                std::fs::copy(&committed, &out)
                    .unwrap_or_else(|e| panic!("no compiled or committed {ext} for {name}: {e}"));
            }
        }
    }
    println!("cargo:rerun-if-env-changed=SLANGC");
}

/// Locate slangc: `SLANGC` env, then PATH, then the default local install.
/// Every candidate (including `SLANGC`) is probed with `-v`, so a bad `SLANGC`
/// value falls through to PATH instead of being reported as a compile failure.
fn find_slangc() -> Option<String> {
    let home = std::env::var("HOME").unwrap_or_default();
    let mut candidates: Vec<String> = Vec::new();
    if let Some(p) = std::env::var_os("SLANGC") {
        candidates.push(p.to_string_lossy().into_owned());
    }
    candidates.push("slangc".to_string());
    candidates.push(format!("{home}/.local/slang/bin/slangc"));
    candidates
        .into_iter()
        .find(|cand| Command::new(cand).arg("-v").output().is_ok())
}
